CallStack (from HasCallStack):
  throwError, called at src/Malgo/Rename/Pass.hs:379:9 in malgo-2.0.0-inplace:Malgo.Rename.Pass
test/Malgo/RenameSpec/errors/DuplicateDef.mlg: line 3, column 1 - line 5, column 1:
Duplicate name: 'fun'